### ISSUE TITLE
Incompatibility with Radium Reforged

### ISSUE THREAD

**Issue by PakoJones88** [AlexiyOrlov/k-turrets#4]
No crash report was generated.

This is the console output:
```java
10:56:12.939
launcher
main
Preparing to launch minecraft client for 1.18.2-forge-40.1.57
10:56:14.867
launcher
main
Minecraft client 1.18.2-forge-40.1.57 is ready to start.
10:56:14.867
launcher
main
Starting!
10:56:15.312
launcher
main
Version does not support log configuration, will assume one plaintext entry per line
10:56:16.593
game
2022-08-02 10:56:16,583 main WARN Advanced terminal features are not available in this environment
10:56:16.707
game
[10:56:16] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, MilitarZ2112, --version, 1.18.2-forge-40.1.57, --gameDir, C:\Users\mmaan\AppData\Roaming\.minecraft, --assetsDir, C:\Users\mmaan\AppData\Roaming\.minecraft\assets, --assetIndex, 1.18, --uuid, 4805fbac304e4ae3baa29d07d538f42b, --accessToken, ????????, --clientId, NzJhZjVkZGItMmNiMC00Yjg0LTkxNzEtMWJiYTI0Nzc3OTlm, --xuid, 2535462651969428, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 40.1.57, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914]
10:56:16.710
game
[10:56:16] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft
10:56:16.798
game
[10:56:16] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/mmaan/AppData/Roaming/.minecraft/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2314!/ Service=ModLauncher Env=CLIENT
10:56:17.095
game
[10:56:17] [main/ERROR] [ne.mi.fm.lo.ModSorter/LOADING]: Missing mandatory dependencies: satako
10:56:17.845
game
[10:56:17] [main/INFO] [mixin/]: Compatibility level set to JAVA_17
10:56:17.845
game
[10:56:17] [main/ERROR] [mixin/]: Mixin config radium.mixins.json does not specify "minVersion" property
10:56:17.856
game
[10:56:17] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'forgeclient' with arguments [--version, 1.18.2-forge-40.1.57, --gameDir, C:\Users\mmaan\AppData\Roaming\.minecraft, --assetsDir, C:\Users\mmaan\AppData\Roaming\.minecraft\assets, --uuid, 4805fbac304e4ae3baa29d07d538f42b, --username, MilitarZ2112, --assetIndex, 1.18, --accessToken, ????????, --clientId, NzJhZjVkZGItMmNiMC00Yjg0LTkxNzEtMWJiYTI0Nzc3OTlm, --xuid, 2535462651969428, --userType, msa, --versionType, release]
10:56:17.955
game
[10:56:17] [main/INFO] [Radium/]: Loaded configuration file for Radium: 100 options available, 0 override(s) found
10:56:19.677
game
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
10:56:19.677
game
at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
10:56:19.677
game
Caused by: java.lang.reflect.InvocationTargetException
10:56:19.677
game
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
10:56:19.677
game
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
10:56:19.677
game
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
10:56:19.677
game
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
10:56:19.677
game
at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.57/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
10:56:19.677
game
at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
10:56:19.677
game
... 7 more
10:56:19.677
game
Caused by: java.lang.RuntimeException: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @6d6bbd35; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6d6bbd35)
10:56:19.677
game
at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.57/net.minecraftforge.fml.loading.BackgroundWaiter.runAndTick(BackgroundWaiter.java:29)
10:56:19.677
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:138)
10:56:19.677
game
... 13 more
10:56:19.677
game
Caused by: java.lang.IllegalAccessError: class me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube tried to access method 'void net.minecraft.world.phys.shapes.VoxelShape.<init>(net.minecraft.world.phys.shapes.DiscreteVoxelShape)' (me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube is in module radium@0.7.10 of loader 'TRANSFORMER' @6d6bbd35; net.minecraft.world.phys.shapes.VoxelShape is in module minecraft@1.18.2 of loader 'TRANSFORMER' @6d6bbd35)
10:56:19.678
game
at TRANSFORMER/radium@0.7.10/me.jellysquid.mods.lithium.common.shapes.VoxelShapeSimpleCube.<init>(VoxelShapeSimpleCube.java:31)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_166049_(Shapes.java:1601)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.m_83048_(Shapes.java:50)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.phys.shapes.Shapes.<clinit>(Shapes.java:26)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Block.m_49796_(Block.java:138)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.SaplingBlock.<clinit>(SaplingBlock.java:20)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.block.Blocks.<clinit>(Blocks.java:59)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverDebugSettings.<clinit>(CarverDebugSettings.java:9)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.m_190634_(CarverConfiguration.java:16)
10:56:19.678
game
at MC-BOOTSTRAP/datafixerupper@4.1.27/com.mojang.serialization.codecs.RecordCodecBuilder.mapCodec(RecordCodecBuilder.java:76)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.CarverConfiguration.<clinit>(CarverConfiguration.java:12)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.carver.WorldCarver.<clinit>(WorldCarver.java:30)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.worldgen.Carvers.<clinit>(Carvers.java:19)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206400_(BuiltinRegistries.java:45)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.m_206392_(BuiltinRegistries.java:101)
10:56:19.678
game
at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.data.BuiltinRegistries.<clinit>(BuiltinRegistries.java:100)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:633)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
10:56:19.678
game
at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
10:56:19.678
game
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
10:56:19.678
game
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
10:56:19.678
game
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
10:56:19.678
game
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
10:56:19.678
game
at java.base/java.lang.Thread.run(Thread.java:833)
10:56:20.209
monitor
Process Monitor
Process crashed with exit code 1
```

**Comment by PakoJones88** [comment]
Nevermind. I have a big modpack and I forgot dependency.
